CREATE TABLE IF NOT EXISTS `local_message_table` (
                                                     `id` bigint NOT NULL COMMENT '主键',
                                                     `tenant_id` varchar(20)     default '000000'           comment '租户编号',
    `class_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '类名',
    `method_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '方法名',
    `method_params` text COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '方法参数',
    `param_types` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '方法类型',
    `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '描述',
    `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'pending' COMMENT '事务执行状态',
    `retry_times` int NOT NULL DEFAULT '0' COMMENT '重试次数',
    `max_retry_times` int NOT NULL DEFAULT '3' COMMENT '最大重试次数',
    `error_message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '错误信息',
    `create_dept`       bigint(20)      default null               comment '创建部门',
    `create_by`         bigint(20)      default null               comment '创建者',
    `create_time`       datetime                                   comment '创建时间',
    `update_by`         bigint(20)      default null               comment '更新者',
    `update_time`       datetime                                   comment '更新时间',
    `executed_time` datetime DEFAULT NULL,
    `user_id` bigint DEFAULT NULL COMMENT '用户ID',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='本地事务消息表';
